version: "3.7"
services:
    testapp:
        restart: 'never'
        image: testapp:testtag
        build:
            context: .
            dockerfile: Dockerfile
            shm_size: '2gb'
        volumes: 
            - type: bind
              source: ./output
              target: /output
        network_mode: host
