version: "3.4"
services:
    testapp:
        restart: 'always'
        image: testapp:testtag
        build:
            context: .
            dockerfile: Dockerfile
        volumes: 
            - type: bind
              source: ./output
              target: /output
